version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=False
      - UPLOAD_FOLDER=/app/temp_uploads
      - OUTPUT_FOLDER=/app/temp_outputs
    volumes:
      - ./temp_uploads:/app/temp_uploads
      - ./temp_outputs:/app/temp_outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for background job processing (commented out for basic deployment)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # Optional: Celery worker for background processing (commented out for basic deployment)
  # worker:
  #   build: .
  #   command: celery -A web.tasks worker --loglevel=info
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   volumes:
  #     - ./temp_uploads:/app/temp_uploads
  #     - ./temp_outputs:/app/temp_outputs
  #   depends_on:
  #     - redis
  #   restart: unless-stopped

volumes:
  redis_data: